#ifndef CONFIG_H
#define CONFIG_H

#define AETHER_VERSION "1.0.0"
#define AETHER_AUTHOR  "iam-skb"

#define MAX_INTERFACES 16
#define MAX_NETWORKS   256
#define MAX_BSSID_LEN  18
#define MAX_SSID_LEN   33

#define DEFAULT_CHANNEL 6
#define DEFAULT_TIMEOUT 30

#define AETHER_TOKEN "AETHER_AUTHORIZED"

#define AETHER_SIMULATE 1

#endif
